version: 2
updates:
  - package-ecosystem: pip
    directory: "/Python Version"
    schedule:
      interval: monthly
    groups:
      python-deps:
        patterns: ["*"]
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    groups:
      dev-deps:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
